/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceEntity
 */
export interface PlaceEntity {
    /**
     * 
     * @type {string}
     * @memberof PlaceEntity
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceEntity
     */
    day?: number;
    /**
     * 
     * @type {string}
     * @memberof PlaceEntity
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceEntity
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceEntity
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceEntity
     */
    lng?: number;
    /**
     * 
     * @type {string}
     * @memberof PlaceEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaceEntity
     */
    timeOfDay?: PlaceEntityTimeOfDayEnum;
    /**
     * 
     * @type {string}
     * @memberof PlaceEntity
     */
    typeOfPlace?: PlaceEntityTypeOfPlaceEnum;
}

export function PlaceEntityFromJSON(json: any): PlaceEntity {
    return PlaceEntityFromJSONTyped(json, false);
}

export function PlaceEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : json['address'],
        'day': !exists(json, 'day') ? undefined : json['day'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lat': !exists(json, 'lat') ? undefined : json['lat'],
        'lng': !exists(json, 'lng') ? undefined : json['lng'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'timeOfDay': !exists(json, 'timeOfDay') ? undefined : json['timeOfDay'],
        'typeOfPlace': !exists(json, 'typeOfPlace') ? undefined : json['typeOfPlace'],
    };
}

export function PlaceEntityToJSON(value?: PlaceEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'day': value.day,
        'description': value.description,
        'id': value.id,
        'lat': value.lat,
        'lng': value.lng,
        'name': value.name,
        'timeOfDay': value.timeOfDay,
        'typeOfPlace': value.typeOfPlace,
    };
}

/**
* @export
* @enum {string}
*/
export enum PlaceEntityTimeOfDayEnum {
    AM = 'AM',
    PM = 'PM',
    SUNRISE = 'SUNRISE',
    SUNSET = 'SUNSET'
}
/**
* @export
* @enum {string}
*/
export enum PlaceEntityTypeOfPlaceEnum {
    AIRPORT = 'AIRPORT',
    ACCOMMODATION = 'ACCOMMODATION',
    TOURISTSPOT = 'TOURIST_SPOT',
    RESTAURANT = 'RESTAURANT',
    OTHER = 'OTHER'
}


